CC = gcc -std=gnu99 -Wall


compile:
	$(CC) -o writer writer.c -O2
	$(CC) -o reader reader.c -O2
	$(CC) -o client client.c -O2
	$(CC) -o customer customer.c -O2

clean:
	rm -rf writer reader client customer 
